### PR TITLE
fix distinct count bug

### PR DESCRIPTION
**Pull request by MarinPostma**
fix https://github.com/meilisearch/meilisearch/issues/2152

I think the issue was that we didn't take off the excluded candidates from the initial candidates when returning the candidates with the search result.

### CODE REVIEW

**Comment by curquiza** [comment]
https://github.com/meilisearch/milli/pull/490 should be merged before this PR since a new check is `Required` to merge the milli PRs: `Specify breaking`

**Review by ManyTheFish — DISMISSED** [review]
LGTM! Thank you @MarinPostma.

Bors merge

**Comment by curquiza** [comment]
bors merge

**Review by curquiza — DISMISSED** [review]
I approve since I only rebased the branch

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors mertge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
