### PR TITLE
Format the whole project

### PR DESCRIPTION
**Pull request by irevoire**
I need to add `cargo fmt` in the CI before closing #231

### CODE REVIEW

**Review by Kerollmops — DISMISSED** [review]

**Comment by Kerollmops** [comment]
Thank you for your time @irevoire, we can now enable our auto-rustfmt editor plugin 🎉 

bors merge

**Comment by irevoire** [comment]
oooh look like we actually need the nightly channel to use the unstable features even though we can continue to build the project in stable.
Should I use the nightly channel in the CI or should I remove the formatting options related to the imports?

**Comment by Kerollmops** [comment]
I don't know if I can set up my `rustfmt` Sublime plugin to run `rustfmt` with the nightly channel, but I will look into this RN.

**Review by Kerollmops — APPROVED** [review]
That's awesome, thank you! 🏈 
bors merge

**Pull request merged**
