### PR TITLE
chore: update dependency

### PR DESCRIPTION
**Pull request by jaeheonji**
Releated Issue https://github.com/meilisearch/MeiliSearch/issues/1888

Hi! meilisearch, I'm currently interested in meilisearch. :)
So I'd like to start contributing from something very simple.

* tokenizer version from `0.2.5` to `0.2.6`

Please let me know if something is wrong 😄

### CODE REVIEW

**Comment by Samyak2** [comment]
The tokenizer dependency is also present in `http-ui`:

https://github.com/meilisearch/milli/blob/2c14efa8a2ce059a12f246fac0f5b34c26153f7a/http-ui/Cargo.toml#L13

**Comment by jaeheonji** [comment]
@Samyak2 Thanks for letting me know what I missed.

**Comment by Kerollmops** [comment]
Hey @jaeheonji,

I am sad about what happened, we didn't see your pull request and we should have answered it before you close it. I hope it will never happen again and I hope next time we will notice your work!

Have a great day,
kero

**Comment by jaeheonji** [comment]
@Kerollmops Thank you for your kindness 😄

**Pull request closed without merging**
