### PR TITLE
Upgrade charabia v0.6.0

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## What does this PR do?

- Update `log`
- Upgrade `charabia`

related to https://github.com/meilisearch/meilisearch/issues/2686

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
👍
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by ManyTheFish** [comment]
bors merge

**Comment by ManyTheFish** [comment]
bors merge

**Comment by ManyTheFish** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
