### PR TITLE
Get rid of the threshold when comparing benchmarks

### PR DESCRIPTION
**Pull request by irevoire**
It just hides things

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
This is a 👍 for me!
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Review by Kerollmops — DISMISSED** [review]
bors merge

**Comment by irevoire** [comment]
bad bors

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Review by curquiza — APPROVED** [review]

**Comment by irevoire** [comment]
good bors

**Pull request merged**
