### PR TITLE
v0.26.3 release: normalizes exact word

### PR DESCRIPTION
**Pull request by curquiza**
`release-v0.26.3` is originated from `v0.26.2` and not from `main`

Add the commits of
- https://github.com/meilisearch/milli/pull/505
- https://github.com/meilisearch/milli/pull/514

And update the version in every concerned files

The tag `v0.26.3` will be created once this PR is merged and will be done on the `release-v0.26.3` branch

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
It's ok kero, you can approve!

**Review by Kerollmops — APPROVED** [review]
I like that!

**Comment by curquiza** [comment]
Waiting for https://github.com/meilisearch/milli/pull/514 to be merged into `main`. Once it's done I will put the commit of this PR into this branch in order to release v0.26.3

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
I've added the https://github.com/meilisearch/milli/pull/505 commit, can you approve again @Kerollmops?

**Review by Kerollmops — APPROVED** [review]

**Comment by Kerollmops** [comment]
bors merge

**Pull request merged**
