### PR TITLE
Fix #652 - Change Spelling of `author` in `README.md`

### LINKED ISSUE #652: [docs] fix spelling of `author` in `README.md`
Hello, and thank you for the awesome search engine!

In `README.md`, the word `author` in the `documents!()` block is spelt `au{hor` in multiple places.

If this is not intentional, I'd like to submit a PR to fix this!

### PR DESCRIPTION
**Pull request by anirudhRowjee**
# Pull Request

## What does this PR do?
Fixes #652
- Changes spellings of `au{hor` to `author`
- Minor formatting changes in Markdown

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by anirudhRowjee** [comment]
Would also be happy to fix the relevant doctest, if need be. Thanks!

**Review by curquiza — APPROVED** [review]
Thanks @anirudhRowjee 

> Would also be happy to fix the relevant doctest, if need be. Thanks!

Please, feel free to fix anything you see if it makes improve the repo quality 😇 

Thanks again

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Thanks again for contributing with Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive a small gift from Meilisearch too, don't forget to fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
