### PR TITLE
Improve the fuzzer of the flatten crate

### PR DESCRIPTION
**Pull request by irevoire**
This somehow ensure that both crates works correctly together

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Nice!
bors merge

**Comment by curquiza** [comment]
Be nice bors, every PR status are ok!

bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
