### PR TITLE
chore: added `IN`,`NOT IN` to `invalid_filter` msg

### PR DESCRIPTION
**Pull request by Pranav-yadav**
# Pull Request

## Related issue
`Fixes` https://github.com/meilisearch/meilisearch/issues/3004

## What does this PR do?
- Improves correct error msg in response

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
This PR fixes https://github.com/meilisearch/meilisearch/issues/3004

PS: do add `hacktoberfest-accepted` before merging :)

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
@Pranav-yadav thanks for your PR

Can you remove the issue from the `Development` (on the right)? I don't want GitHub to close the issue on Meilisearch side when merging this PR 😇

**Comment by irevoire** [comment]
Hey @Pranav-yadav, I think you forgot to update the tests.

**Comment by Pranav-yadav** [comment]
> Hey @Pranav-yadav, I think you forgot to update the tests.

Oops! On it..

**Comment by Pranav-yadav** [comment]
@irevoire can you guide me w/ fixing tests ?
I'm newbie in rust and it's stuff..

**Comment by Pranav-yadav** [comment]
@curquiza Ohh! I though it's directly related issue hence mentioned..

**Comment by curquiza** [comment]
@Pranav-yadav it's ok now! thanks 😇

**Comment by Pranav-yadav** [comment]
> @irevoire can you guide me w/ fixing tests ? I'm newbie in rust and it's stuff..
> 
> ran `cargo test`: image

Did this much [3950ec8](https://github.com/meilisearch/milli/commit/3950ec8d3c8cdd501fb5c9e47abf78271d3613c4) , is it correct?

**Comment by irevoire** [comment]
Hey @Pranav-yadav, sorry that's an issue on our side, thanks for noticing I will open an issue for running the whole test suite in our CI and update our CONTRIBUTING.md maybe.

> Did this much [3950ec8](https://github.com/meilisearch/milli/commit/3950ec8d3c8cdd501fb5c9e47abf78271d3613c4) , is it correct?

Yes this is perfect, thanks for your contribution!

bors merge

Since our issue has some issues currently I'm going to manually mark your PR as `hacktoberfest-accepted`, thus even if it doesn't merge your contribution will be marked as valid (in case you registered to participate to the hacktoberfest).
And in any case, if you want to receive some swag from Meilisearch, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY), we only do it during the hacktoberfest 😁

**Review by irevoire — APPROVED** [review]
thanks!

**Pull request merged**
