### PR TITLE
Return facets even when there is no value associated to it

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR is related to https://github.com/meilisearch/meilisearch/issues/2352 and should fix the issue when Meilisearch is up-to-date with this PR.

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
:+1:

**Comment by Kerollmops** [comment]
I will let @curquiza decide on wether we merge it now/here or not.

**Comment by curquiza** [comment]
What would be the issue to merge it @Kerollmops?
If it's technically ok for you, feel free to merge it into main. I will release milli v0.26.4

**Comment by Kerollmops** [comment]
Thank you, I merge this!
bors merge

**Pull request merged**
