### PR TITLE
feat(search, criteria): const candidates threshold

### PR DESCRIPTION
**Pull request by shekhirin**
Resolves https://github.com/meilisearch/milli/issues/49

### CODE REVIEW

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much 🙏

I would like to ask you to change the PR a little bit, could you, please, define a const of 1000, named `CANDIDATES_THRESHOLD` as you've already done?

We have two types of algorithms, a linear one, that fetches documents facet values one by one and does a basic sort, and a set-theory-based algorithm that efficiently iterates over the facet values.

The goal of the threshold is to help us choose between both algorithms, it is much more correct to use the linear algorithm on a fixed number of documents instead of a ratio of the number of documents in the database.

**Comment by shekhirin** [comment]
Ok, got it. So do I get it right that issue https://github.com/meilisearch/milli/issues/49 doesn't make much sense? 😄

**Comment by Kerollmops** [comment]
@shekhirin Yeah, indeed, it is quite outdated. It was created a long time ago and I didn't take the time to update it, sorry for that. Anyway, your PR will close it :)

**Comment by shekhirin** [comment]
@Kerollmops ok, no problem! :) Thanks for clarification. Btw, I've updated the PR with const threshold definition.

**Review by Kerollmops — APPROVED** [review]
This is good for me, thank you for your contribution.

Hope to see you on another PR, I will create other "first good issues" issues 😃

**Pull request merged**
