### PR TITLE
fix cargo warnings

### PR DESCRIPTION
**Pull request by MarinPostma**
fix cargo warnings

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Ok, so this is the PR that will make https://github.com/meilisearch/milli/pull/507 to pass the CI again!
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
@curquiza do you think I can merge by hand, here?

**Comment by curquiza** [comment]
I don't know how it's possible this is up-to-date with `main`... can we rebase it before merging by hand?

**Review by Kerollmops — APPROVED** [review]
bors merge

**Pull request merged**
