### PR TITLE
fix(criterion): compile asc/desc regex only once

### PR DESCRIPTION
**Pull request by shekhirin**
Resolves https://github.com/meilisearch/milli/issues/129

### CODE REVIEW

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much again,

Seems good to me, however, could you please squash all the commits (including the merge commit) into only one, please?

**Comment by shekhirin** [comment]
@Kerollmops yep, sure, but can't you do so while merging the PR selecting `Squash and merge` on GitHub?

**Comment by Kerollmops** [comment]
Yeah sure but the problem with that option is that Github will not create a merge commit that I want to more easily keep track of the original PR in the list of commits on `main`.

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Could you please pull `main` and rebase, please?

**Comment by shekhirin** [comment]
@Kerollmops yep, done

**Review by Kerollmops — APPROVED** [review]
Thank you very much :)

**Pull request merged**
