### PR TITLE
exporting heed to avoid having different versions of Heed in Meilisearch

### PR DESCRIPTION
**Pull request by psvnlsaikumar**
# Pull Request

## What does this PR do?
Fixes the issue in meilisearch https://github.com/meilisearch/meilisearch/issues/2210

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Thank you very much, merging!
bors merge

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Whoops, could you do a rustfmt pass, please?

```
cargo +nightly fmt
```

**Comment by psvnlsaikumar** [comment]
@Kerollmops  Performed cargo +nightly fmt . I hope that this was the expectation.

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by Kerollmops** [comment]
This PR is breaking as, even if it is the same version as before, cargo/rustc is not smart enough to understand that and makes calling crates break.

**Pull request merged**
