### PR TITLE
Fix hard-deletion of an external id that was soft-deleted and then reimported - release-v0.37.5

### PR DESCRIPTION
**Pull request by loiclec**
This is a PR that cherry-picks the commit from https://github.com/meilisearch/milli/pull/750 onto `release-v0.37.5`

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
I approve the fact the PR is going to be merged into the right branch, but I don't approve the code of course 👌 

thanks lo!

**Review by irevoire — APPROVED** [review]
Did you run your fuzzer again on this branch, just in case? :eyes:

**Comment by irevoire** [comment]
bors merge

**Comment by loiclec** [comment]
Yes, the fuzz test was done on this branch initially :-)

**Pull request merged**
