### PR TITLE
Reserved keyword error message

### PR DESCRIPTION
**Pull request by irevoire**
And I missed _another_ reserved keyword error message in the filter :(

### CODE REVIEW

**Comment by irevoire** [comment]
I tested this in meilisearch and I get the expected result:
image

**Comment by irevoire** [comment]
oops wait maybe we're going to change the message for `_geo`

**Comment by irevoire** [comment]
Here are the new error messages:
image

And here is the spec patch:
https://github.com/meilisearch/specifications/pull/79/files

**Review by curquiza — DISMISSED** [review]
I always feel a little bit lost in the middle of all these errors, but as far as I understand, it looks good to me 😇

**Comment by irevoire** [comment]
I added `.` to the end of each error like in the spec but it's ready to be merged :+1:

**Review by Kerollmops — APPROVED** [review]
Thank you tamotamo!
bors merge

**Pull request merged**
