### PR TITLE
Stop tracking the Cargo.lock and add cache + windows to the CI

### PR DESCRIPTION
**Pull request by irevoire**
We reuse the same `~/.cargo` and `./target` directory between each run on the same OS and rust toolchain.
The `key` to decide if we can use the cache or not is: `$OS_NAME-$RUST_TOOLCHAIN-$HASH(Cargo.toml)`

We also removed the `Cargo.lock` from this repository. Indeed, milli is a library and [should not track the `Cargo.lock`](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)

And finally, we enabled the tests on `windows-latest`. Since `lmdb` has been updated, this is now possible.

### CODE REVIEW

**Comment by irevoire** [comment]
I had no luck on the last run, it took a really long time to find a macOS workers. But apart from that, the CI look really faster, I think we can merge that.

Since I'm on it do you think we should run the tests on windows now? (it works on transplant so it should also works on milli)

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Indeed, it would be great to test on Windows.
Could you also remove the Cargo.lock, add it to the .gitignore and patch the CI to not check with `--locked`?

**Review by Kerollmops — APPROVED** [review]
Seems good to me, thank you!
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by irevoire** [comment]
bors cancel

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by curquiza** [comment]
It should work now

**Comment by curquiza** [comment]
bors merge

**Review by curquiza — APPROVED** [review]

**Pull request merged**
