### PR TITLE
Release v0.26.4: returns facets even when there is no value associated to it + bug fix during indexation + bug fix on typo-tolerance

### PR DESCRIPTION
**Pull request by curquiza**
I cherry-picked the commits from these PRs
- https://github.com/meilisearch/milli/pull/518
- https://github.com/meilisearch/milli/pull/522
- https://github.com/meilisearch/milli/pull/520

`release-v0.26.4` has been started from the tag `v0.26.3` and not from main

The release tag `v0.26.4` will be done on the branch `release-v0.26.4` once this PR is merge

### CODE REVIEW

**Comment by curquiza** [comment]
Don't merge it until we take a decision if this should be fixed or not: https://github.com/meilisearch/meilisearch/issues/2358

**Comment by curquiza** [comment]
bors try

**Review by ManyTheFish — APPROVED** [review]

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
Still missing https://github.com/meilisearch/milli/pull/520 to be put into this PR, sorry

**Review by Kerollmops — APPROVED** [review]
bors merge

**Pull request merged**
